spring:
#    datasource:
#        url: jdbc:mysql://localhost:3306/toptal_db
#        username: ${DB_USERNAME}
#        password: ${DB_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: create-drop
